/*
 * Automatically generated C config: don't edit
 */
#undef RTCONFIG_FW_JUMP
#undef RTCONFIG_REALTEK
#undef RTCONFIG_RTL819X
#undef RTCONFIG_RTL8197F
#undef RTCONFIG_RTK_NAND
#define RTCONFIG_OPTIMIZE_SHARED_LIBS 1
#undef RTCONFIG_MUSL_LIBC
#define RTCONFIG_L2TP 1
#define RTCONFIG_PPTP 1
#define RTCONFIG_EAPOL 1
#undef RTCONFIG_PPTPD
#define RTCONFIG_ACCEL_PPTPD 1
#define RTCONFIG_SNMPD 1
#define RTCONFIG_HTTPS 1
#define RTCONFIG_BCMARM 1
#undef RTCONFIG_BCM7
#undef RTCONFIG_BCM_794
#undef RTCONFIG_BCM_7114
#define RTCONFIG_HND_ROUTER 1
#undef RTCONFIG_BCM_MFG
#undef RTCONFIG_WLTEST
#undef RTCONFIG_FW_CHK_BOARDID
#define RTCONFIG_HND_ROUTER_AX 1
#undef RTCONFIG_HND_ROUTER_AX_675X
#undef RTCONFIG_HND_ROUTER_AX_6756
#define RTCONFIG_HND_ROUTER_BE_4916 1
#undef RTCONFIG_HND_ROUTER_AX_6710
#undef RTCONFIG_SDK504L02_188_1303
#undef RTCONFIG_BCM_502L07P2
#undef RTCONFIG_BCM_WIFI_NIC_DEBUG
#undef RTCONFIG_HND_WL
#undef RTCONFIG_DFS_US
#undef RTCONFIG_BCM9
#undef RTCONFIG_BUILDBCM7
#undef RTCONFIG_ROMCFE
#undef RTCONFIG_ROMATECCODEFIX
#undef RTCONFIG_NV128
#define RTCONFIG_NVRAM_SIZE 0x30000
#define RTCONFIG_DHDAP 1
#define RTCONFIG_BW160M 1
#define RTCONFIG_BW320M 1
#define RTCONFIG_WLEXE 1
#undef RTCONFIG_DPSTA
#undef RTCONFIG_DPSR
#undef RTCONFIG_GMAC3
#define RTCONFIG_BCMSMP 1
#undef RTCONFIG_BCMFA
#undef RTCONFIG_RGMII_BCM_FA
#undef RTCONFIG_5301X
#undef RTCONFIG_4352_5G
#define RTCONFIG_SSH 1
#undef RTCONFIG_CIFS
#undef RTCONFIG_BRCM_NAND_JFFS2
#define RTCONFIG_JFFS_NVRAM 1
#undef RTCONFIG_JFFS_NVRAM_HND_OLD
#undef RTCONFIG_JFFS2
#undef RTCONFIG_MXL371X
#undef RTCONFIG_MOCA
#undef RTCONFIG_DISKTEST
#undef RTCONFIG_ZEBRA
#define RTCONFIG_QUAGGA 1
#define RTCONFIG_DDNS 1
#define RTCONFIG_INADYN 1
#undef RTCONFIG_L7
#define RTCONFIG_LZO 1
#define RTCONFIG_OPENVPN 1
#define RTCONFIG_IPSEC 1
#undef RTCONFIG_QUICKSEC
#define RTCONFIG_STRONGSWAN 1
#define RTCONFIG_IPSEC_SERVER 1
#undef RTCONFIG_IPSEC_CLIENT
#define RTCONFIG_IPV6 1
#undef RTCONFIG_IPV6_PRIVACY
#undef RTCONFIG_IMPROXY
#define RTCONFIG_EBTABLES 1
#define RTCONFIG_EMF 1
#define RTCONFIG_BCMBSD 1
#define RTCONFIG_BCMBSD_V2 1
#undef RTCONFIG_BCMSSD
#define RTCONFIG_BCMDCS 1
#undef RTCONFIG_TOAD
#undef RTCONFIG_BCM_MEVENT
#define RTCONFIG_BCMEVENTD 1
#undef RTCONFIG_BCM_APPEVENTD
#undef RTCONFIG_HSPOT
#undef RTCONFIG_FANCTRL
#define RTCONFIG_BCMWL6 1
#define RTCONFIG_BCMWL6A 1
#undef RTCONFIG_BCM4708
#undef RTCONFIG_WIRELESSWAN
#define RTCONFIG_WIRELESSREPEATER 1
#undef RTCONFIG_REPEATER
#undef RTCONFIG_DISABLE_REPEATER_UI
#define RTCONFIG_PROXYSTA 1
#undef RTCONFIG_DISABLE_PROXYSTA_UI
#define RTCONFIG_PSR_GUEST 1
#undef RTCONFIG_CONCURRENTREPEATER
#undef RTCONFIG_WISP
#undef RTCONFIG_VHT80_80
#undef RTCONFIG_VHT160
#undef RTCONFIG_IXIAEP
#undef RTCONFIG_IPERF
#undef RTCONFIG_TCPDUMP
#undef RTCONFIG_DUMP4000
#define RTCONFIG_TRACEROUTE 1
#define RTCONFIG_NETOOL 1
#define RTCONFIG_PARENTALCTRL 1
#define RTCONFIG_INTERNETCTRL 1
#define RTCONFIG_DNSPRIVACY 1
#undef RTCONFIG_DSL
#undef RTCONFIG_DSL_ANNEX_B
#undef RTCONFIG_DSL_TCLINUX
#undef RTCONFIG_VDSL
#undef RTCONFIG_DSL_BCM
#undef RTCONFIG_DSL_HOST
#undef RTCONFIG_DSL_REMOTE
#undef RTCONFIG_SFPP
#define RTCONFIG_SYSSTATE 1
#undef RTCONFIG_AHS
#define RTCONFIG_LIBASC 1
#define RTCONFIG_DUALWAN 1
#undef RTCONFIG_HW_DUALWAN
#undef RTCONFIG_MFGFW
#undef RTCONFIG_USER_LOW_RSSI
#undef RTCONFIG_WATCH_WLREINIT
#undef RTCONFIG_WATCH_WLRXF1OVFL
#define RTCONFIG_NEW_USER_LOW_RSSI 1
#undef RTCONFIG_FRS_FEEDBACK
#define RTCONFIG_PUSH_EMAIL 1
#undef RTCONFIG_RSYSLOGD
#define RTCONFIG_DBLOG 1
#undef RTCONFIG_NO_USBPORT
#define RTCONFIG_USB 1
#define RTCONFIG_USB_WAN_BACKUP 1
#undef RTCONFIG_USBRESET
#undef RTCONFIG_WIFIPWR
#undef RTCONFIG_XHCIMODE
#define RTCONFIG_MEDIA_SERVER 1
#undef RTCONFIG_MEDIASERVER_LIMIT
#undef RTCONFIG_NO_DAAPD
#define RTCONFIG_CLOUDSYNC 1
#define RTCONFIG_SWEBDAVCLIENT 1
#define RTCONFIG_DROPBOXCLIENT 1
#define RTCONFIG_GOOGLECLIENT 1
#define RTCONFIG_FTPCLIENT 1
#define RTCONFIG_SAMBACLIENT 1
#define RTCONFIG_USBCLIENT 1
#undef RTCONFIG_FLICKRCLIENT
#define RTCONFIG_FTP 1
#define RTCONFIG_FTP_SSL 1
#define RTCONFIG_WEBDAV 1
#define RTCONFIG_SAMBASRV 1
#undef RTCONFIG_SAMBA3
#define RTCONFIG_AWSIOT 1
#define RTCONFIG_SAMBA36X 1
#undef RTCONFIG_SAMBA4
#define RTCONFIG_USB_EXTRAS 1
#define RTCONFIG_E2FSPROGS 1
#undef RTCONFIG_EXT4FS
#define RTCONFIG_TFAT 1
#undef RTCONFIG_OPENPLUS_TFAT
#define RTCONFIG_NTFS 1
#undef RTCONFIG_PARAGON_NTFS
#define RTCONFIG_TUXERA_NTFS 1
#undef RTCONFIG_OPEN_NTFS3G
#define RTCONFIG_HFS 1
#undef RTCONFIG_PARAGON_HFS
#define RTCONFIG_TUXERA_HFS 1
#undef RTCONFIG_KERNEL_HFSPLUS
#undef RTCONFIG_APFS
#define RTCONFIG_DISK_MONITOR 1
#define RTCONFIG_USB_PRINTER 1
#undef RTCONFIG_USB_CDROM
#define RTCONFIG_USB_MODEM 1
#undef RTCONFIG_USB_LESSMODEM
#define RTCONFIG_USB_MODEM_PIN 1
#undef RTCONFIG_USB_SMS_MODEM
#undef RTCONFIG_USB_MULTIMODEM
#undef RTCONFIG_INTERNAL_GOBI
#undef RTCONFIG_QFIREHOSE
#undef RTCONFIG_DYN_MODEM
#undef RTCONFIG_BRCM_USBAP
#undef RTCONFIG_APP_PREINSTALLED
#define RTCONFIG_APP_NETINSTALLED 1
#undef RTCONFIG_APP_FILEFLEX
#undef RTCONFIG_RALINK
#undef RTCONFIG_NEWSSID_REV2
#define RTCONFIG_NEWSSID_REV4 1
#undef RTCONFIG_NEWSSID_REV5
#undef RTCONFIG_RP_NEWSSID_REV3
#undef RTCONFIG_QCA
#undef RTCONFIG_QCA_BIGRATE_WIFI
#define RTCONFIG_NEW_APP_ARM 1
#undef RTCONFIG_QCA_ARM
#undef RTCONFIG_QCA953X
#undef RTCONFIG_QCA956X
#undef RTCONFIG_QCN550X
#undef RTCONFIG_SOC_IPQ40XX
#undef RTCONFIG_SOC_IPQ60XX
#undef RTCONFIG_SOC_IPQ50XX
#undef RTCONFIG_FITFDT
#undef RTCONFIG_QCA_VAP_LOCALMAC
#undef RTCONFIG_QCA_PLC_UTILS
#undef RTCONFIG_AR7420
#undef RTCONFIG_QCA7500
#undef RTCONFIG_AIR_TIME_FAIRNESS
#undef RTCONFIG_POWER_SAVE
#undef RTCONFIG_PAGECACHE_RATIO
#undef RTCONFIG_QCA8033
#undef RTCONFIG_ART2_BUILDIN
#undef RTCONFIG_DEFAULT_AP_MODE
#undef RTCONFIG_DEFAULT_REPEATER_MODE
#define RTCONFIG_ODMPID 1
#undef RTCONFIG_32BYTES_ODMPID
#define RTCONFIG_TIMEMACHINE 1
#define RTCONFIG_MDNS 1
#undef RTCONFIG_FINDASUS
#undef RTCONFIG_REDIRECT_DNAME
#undef RTCONFIG_MTK_TW_AUTO_BAND4
#undef RTCONFIG_QCA_TW_AUTO_BAND4
#undef RTCONFIG_LED_ALL
#undef RTCONFIG_COMA
#define CONFIG_LIBBCM 1
#undef CONFIG_LIBUPNP
#undef RTCONFIG_MFP
#define RTCONFIG_WPS 1
#undef RTCONFIG_NFC
#undef RTCONFIG_WPS_ENROLLEE
#undef RTCONFIG_SHP
#undef RTCONFIG_SFP
#undef RTCONFIG_STRACE
#undef RTCONFIG_4M_SFP
#undef RTCONFIG_8M_SFP
#undef RTCONFIG_16M_RAM_SFP
#undef RTCONFIG_GROCTRL
#undef RTCONFIG_LANWAN_LED
#undef RTCONFIG_WLAN_LED
#define RTCONFIG_FAKE_ETLAN_LED 1
#undef RTCONFIG_EXT_LED_WPS
#undef RTCONFIG_SWMODE_SWITCH
#undef RTCONFIG_WL_AUTO_CHANNEL
#undef RTCONFIG_SMALL_FW_UPDATE
#undef RTCONFIG_WIRELESS_SWITCH
#define RTCONFIG_WIFI_TOG_BTN 1
#undef RTCONFIG_WPS_RST_BTN
#undef RTCONFIG_WPS_ALLLED_BTN
#define RTCONFIG_SW_CTRL_ALLLED 1
#define RTCONFIG_TURBO_BTN 1
#undef RTCONFIG_LOGO_LED
#undef RTCONFIG_LED_BTN
#undef RTCONFIG_USBEJECT
#define RTCONFIG_AUTODICT 1
#undef RTCONFIG_AUTOLIVEUPDATE_ZIP
#undef RTCONFIG_ISP_METER
#undef RTCONFIG_NVRAM_64K
#define RTCONFIG_USB_XHCI 1
#undef RTCONFIG_WLMODULE_RT3090_AP
#undef RTCONFIG_WLMODULE_RT3352_INIC_MII
#undef RTCONFIG_WLMODULE_MT7610_AP
#undef RTCONFIG_WLMODULE_RLT_WIFI
#undef RTCONFIG_WLMODULE_MT7603E_AP
#undef RTCONFIG_WLMODULE_MT7628_AP
#undef RTCONFIG_WLMODULE_MT7615E_AP
#undef RTCONFIG_WLMODULE_MT7663E_AP
#undef RTCONFIG_WLMODULE_MT7629_AP
#undef RTCONFIG_WLMODULE_MT7622_AP
#undef RTCONFIG_WLMODULE_MT7915D_AP
#define RTCONFIG_PSISTLOG 1
#undef RTCONFIG_DUAL_TRX
#undef RTCONFIG_TEST_FLIPBITS
#define RTCONFIG_UBI 1
#define RTCONFIG_UBIFS 1
#undef RTCONFIG_YAFFS
#undef RTCONFIG_SAVEJFFS
#define RTCONFIG_OPTIMIZE_XBOX 1
#undef RTCONFIG_NEW_REGULATION_DOMAIN
#undef RTCONFIG_DYN_DICT_NAME
#undef RTCONFIG_LAN4WAN_LED
#undef RTCONFIG_DMALLOC
#undef RTCONFIG_JFFS2ND_BACKUP
#undef RTCONFIG_TEMPROOTFS
#undef RTCONFIG_SINGLEIMG_B
#undef RTCONFIG_ATEUSB3_FORCE
#undef RTCONFIG_WPSMULTIBAND
#undef RTCONFIG_RALINK_DFS
#undef RTCONFIG_ENGINEERING_MODE
#define RTCONFIG_VPNC 1
#undef RTCONFIG_KYIVSTAR
#undef RTCONFIG_NO_WANPORT
#undef RTCONFIG_WANPORT2
#undef RTCONFIG_MULTIWAN_CFG
#define RTCONFIG_MULTILAN_CFG 1
#undef RTCONFIG_MULTIWAN_IF
#undef RTCONFIG_MULTIWAN_PROFILE
#undef RTCONFIG_BUSINESS
#undef RTCONFIG_UI4
#undef RTCONFIG_SMART_HOME_MASTER_UI
#define RTCONFIG_SDN_PRIORITY 1
#define RTCONFIG_MAX_MTLAN 8
#define RTCONFIG_MULTILAN_MWL 1
#undef RTCONFIG_TFTP_SERVER
#undef RTCONFIG_AI_SERVICE
#undef RTCONFIG_ETRON_XHCI
#undef RTCONFIG_ETRON_XHCI_USB3_LED
#undef RTCONFIG_WPS_LED
#undef RTCONFIG_MMC_LED
#undef RTCONFIG_RESET_SWITCH
#undef RTCONFIG_WANRED_LED
#undef RTCONFIG_WANLEDX2
#undef RTCONFIG_R10G_LED
#undef RTCONFIG_PWRRED_LED
#undef RTCONFIG_SATA_LED
#undef RTCONFIG_BLINK_LED
#undef RTCONFIG_LEDS_CLASS
#undef RTCONFIG_EJUSB_BTN
#undef RTCONFIG_M2_SSD
#undef RTCONFIG_WIGIG
#undef RTCONFIG_CFE_NVRAM_CHK
#undef RTCONFIG_DEBUG
#undef RTCONFIG_VALGRIND
#define RTCONFIG_HAS_5G 1
#define RTCONFIG_HAS_5G_2 1
#undef RTCONFIG_TFTP
#undef RTCONFIG_QTN
#undef RTCONFIG_ALPINE
#undef RTCONFIG_QSR10G
#undef RTCONFIG_LANTIQ
#undef RTCONFIG_N18UTXBF
#undef RTCONFIG_HNS
#define RTCONFIG_BWDPI 1
#undef RTCONFIG_TRAFFIC_LIMITER
#undef RTCONFIG_SPEEDTEST
#define RTCONFIG_BONDING 1
#undef RTCONFIG_BONDING_WAN
#undef RTCONFIG_UIDEBUG
#undef RTCONFIG_DEMOUI
#undef RTCONFIG_TS_UI
#define RTCONFIG_ADGUARDDNS 1
#define RTCONFIG_ROG 1
#define RTCONFIG_ROG_UI 1
#undef RTCONFIG_GS_UI
#undef RTCONFIG_TUF_UI
#undef RTCONFIG_GEOIP
#undef RTCONFIG_GEOIP_EG
#undef RTCONFIG_TRANSMISSION
#define RTCONFIG_TCODE 1
#undef RTCONFIG_WIFILOGO
#define RTCONFIG_JFFS2USERICON 1
#undef RTCONFIG_EXT_RTL8365MB
#undef RTCONFIG_EXT_RTL8370MB
#undef RTCONFIG_EXT_BCM53134
#undef RTCONFIG_EXT_RTL8367S
#undef RTCONFIG_RTL8221VB
#define RTCONFIG_EXTPHY_BCM84880 1
#define RTCONFIG_BCM_HND_CRASHLOG 1
#define RTCONFIG_TOR 1
#undef RTCONFIG_TR069
#undef RTCONFIG_TR181
#undef RTCONFIG_ISP_OPTUS
#undef RTCONFIG_ACS_SUBNET
#undef RTCONFIG_ISP_XLNPROVU
#define RTCONFIG_STAINFO 1
#undef RTCONFIG_CLOUDCHECK
#define RTCONFIG_GETREALIP 1
#undef CONFIG_ASUS_APCLI_WPS
#define RTCONFIG_TUNNEL 1
#undef RTCONFIG_UPLOADER
#define RTCONFIG_AICLOUD_TUNNEL 1
#define RTCONFIG_AIHOME_TUNNEL 1
#undef RTCONFIG_UAC_TUNNEL
#define RTCONFIG_CFEZ 1
#undef RTCONFIG_RESTRICT_GUI
#define RTCONFIG_LACP 1
#undef RTCONFIG_KEY_GUARD
#undef RTCONFIG_RECVFILE
#undef RTCONFIG_WTFAST
#define RTCONFIG_WTFAST_V2 1
#define RTCONFIG_ALEXA 1
#undef RTCONFIG_IFTTT
#define RTCONFIG_UTF8_SSID 1
#undef RTCONFIG_ERP_TEST
#define RTCONFIG_REBOOT_SCHEDULE 1
#define RTCONFIG_REBOOT_SCHEDULE_V2 1
#define RTCONFIG_CAPTIVE_PORTAL 1
#define RTCONFIG_CP_FREEWIFI 1
#undef RTCONFIG_CP_ADVANCED
#undef RTCONFIG_UPNPC
#undef RTCONFIG_UPNPC_NEW
#undef RTCONFIG_AUPNPC
#define RTCONFIG_MULTICAST_IPTV 1
#undef RTCONFIG_BONJOUR
#undef RTCONFIG_FORCE_AUTO_UPGRADE
#undef RTCONFIG_CHILLISPOT
#define RTCONFIG_COOVACHILLI 1
#undef RTCONFIG_FREERADIUS
#undef RTCONFIG_TUXERA_SMBD
#undef RTCONFIG_BCMASPMD
#undef RTCONFIG_FBT
#undef RTCONFIG_WLCLMLOAD
#define RTCONFIG_MUMIMO 1
#define RTCONFIG_NOTIFICATION_CENTER 1
#define RTCONFIG_PROTECTION_SERVER 1
#define RTCONFIG_WLCEVENTD 1
#undef RTCONFIG_HAPDEVENT
#define RTCONFIG_6RELAYD 1
#define RTCONFIG_SOFTWIRE46 1
#define RTCONFIG_OCNVC 1
#define RTCONFIG_V6OPTION 1
#define RTCONFIG_DSLITE 1
#undef RTCONFIG_PORT_BASED_VLAN
#undef RTCONFIG_TAGGED_BASED_VLAN
#undef RTCONFIG_DISABLE_NETWORKMAP
#undef RTCONFIG_WAN_AT_P4
#undef RTCONFIG_MTK_REP
#undef RTCONFIG_ATED122
#undef RTCONFIG_NOIPTV
#undef RTCONFIG_MTK_NAND
#undef RTCONFIG_RALINK_EDCCA
#define RTCONFIG_AUTOCOVER_SIP 1
#undef RTCONFIG_DEFLAN50
#define RTCONFIG_ALL_DEF_LAN50 1
#define RTCONFIG_VPN_FUSION 1
#define RTCONFIG_VPN_FUSION_SUPPORT_INTERFACE 1
#define RTCONFIG_LBR_AGGR 1
#undef RTCONFIG_FLATLAS
#undef RTCONFIG_WBD
#undef RTCONFIG_QAM256_2G
#undef RTCONFIG_QAM1024_5G
#undef RTCONFIG_MUMIMO_2G
#undef RTCONFIG_MUMIMO_5G
#define RTCONFIG_CONNTRACK 1
#undef RTCONFIG_PERMISSION_MANAGEMENT
#undef RTCONFIG_NANO
#define RTCONFIG_TELENET 1
#undef RTCONFIG_NFS
#define RTCONFIG_IGD2 1
#define RTCONFIG_DNSSEC 1
#undef RTCONFIG_DNSSEC_OPENSSL
#define RTCONFIG_DNSSEC_NETTLE 1
#undef RTCONFIG_MERLINUPDATE
#define RTCONFIG_VPN_FUSION_MERLIN 1
#undef RTCONFIG_OPENSSL11
#define RTCONFIG_DNSFILTER 1
#define RTCONFIG_LETSENCRYPT 1
#undef RTCONFIG_DETWAN
#define RTCONFIG_CFGSYNC 1
#define RTCONFIG_CFGSYNC_LOCSYNC 1
#undef RTCONFIG_LP5523
#undef RTCONFIG_ZENWIFI_RGBLED
#undef RTCONFIG_AURA_RGBLED
#undef RTCONFIG_GPIOX3_RGBLED
#undef RTCONFIG_PWMX1_GPIOX3_RGBLED
#undef RTCONFIG_PWMX2_GPIOX1_RGBLED
#undef RTCONFIG_PWMX3_RGBLED
#undef RTCONFIG_SINGLE_SSID
#undef RTCONFIG_SSID_AMAPS
#undef RTCONFIG_PTHSAFE_POPEN
#undef RTCONFIG_HIDDEN_BACKHAUL
#undef RTCONFIG_ETHBACKHAUL
#undef RTCONFIG_AUTHSUPP
#undef RTCONFIG_FBWIFI
#define RTCONFIG_ADV_RAST 1
#define RTCONFIG_BCN_RPT 1
#define RTCONFIG_MC_BCN_RPT 1
#define RTCONFIG_NBR_RPT 1
#undef RTCONFIG_ADTBW_AFTER_RADARDETECTED
#define RTCONFIG_BTM_11V 1
#undef RTCONFIG_FAST_ACL_SET
#define RTCONFIG_FORCE_ROAMING 1
#define RTCONFIG_STA_AP_BAND_BIND 1
#define RTCONFIG_11K_RCPI_CHECK 1
#undef RTCONFIG_RAST_NONMESH_KVONLY
#undef RTCONFIG_RAST_TEST
#define RTCONFIG_CONN_EVENT_TO_EX_AP 1
#undef RTCONFIG_WLCSCAN_RSSI
#undef RTCONFIG_VISUALIZATION
#undef RTCONFIG_BT_CONN
#undef RTCONFIG_BT_CONN_USB
#undef RTCONFIG_BT_CONN_UART
#undef RTCONFIG_CSR8811
#undef RTCONFIG_RGBLED
#define RTCONFIG_BCM_CLED 1
#undef RTCONFIG_SINGLE_LED
#undef RTCONFIG_PIPEFW
#undef RTCONFIG_URLFW
#undef RTCONFIG_AURASYNC
#define RTCONFIG_I2CTOOLS 1
#undef RTCONFIG_MTK_8021X3000
#undef RTCONFIG_MTK_8021XD3000
#undef RTCONFIG_INTEL
#undef RTCONFIG_DBG_BLUECAVE_OBD
#define RTCONFIG_AMAS 1
#undef RTCONFIG_AMAS_WGN
#undef RTCONFIG_AMASDB
#undef RTCONFIG_BATMAN_ADV
#define RTCONFIG_AVBLCHAN 1
#undef RTCONFIG_LYRA_5G_SWAP
#undef RTCONFIG_NO_SELECT_CHANNEL
#undef RTCONFIG_USB_SWAP
#undef RTCONFIG_SW_DEVLED
#undef RTCONFIG_LYRA_HIDE
#undef RTCONFIG_PORT2_DEVICE
#define RTCONFIG_NVRAM_ENCRYPT 1
#undef RTCONFIG_WIFI_PROXY
#define RTCONFIG_HD_SPINDOWN 1
#define RTCONFIG_MASTER_DET 1
#undef RTCONFIG_ADTBW
#undef RTCONFIG_TXBF_BAND3ONLY
#define RTCONFIG_SW_HW_AUTH 1
#define RTCONFIG_LIBASUSLOG 1
#define RTCONFIG_BCM_CEVENTD 1
#define RTCONFIG_ETHOBD 1
#define RTCONFIG_DWB 1
#undef RTCONFIG_NO_TRY_DWB_PROFILE
#undef RTCONFIG_FRONTHAUL_DWB
#define RTCONFIG_AMAS_ETHDETECT 1
#define RTCONFIG_BHCOST_OPT 1
#define RTCONFIG_CONNDIAG 1
#undef RTCONFIG_DASHBOARD
#undef RTCONFIG_CABLEDIAG
#undef RTCONFIG_CD_IPERF
#undef RTCONFIG_REPEATER_STAALLBAND
#define RTCONFIG_NTPD 1
#undef RTCONFIG_WTF_REDEEM
#undef RTCONFIG_QCA_LBD
#undef RTCONFIG_AMAS_WDS
#undef RTCONFIG_AMAS_MTK_EZWDS
#undef RTCONFIG_MTK_BSD
#undef RTCONFIG_SW_BTN
#undef RTCONFIG_COBRAND
#undef RTCONFIG_GEFORCENOW
#undef RTCONFIG_FPROBE
#undef RTCONFIG_ISP_CUSTOMIZE
#undef RTCONFIG_IPERF3
#undef RTCONFIG_NFCM
#define RTCONFIG_DNSQUERY_INTERCEPT 1
#undef RTCONFIG_ROUTERBOOST
#define RTCONFIG_ASUSCTRL 1
#undef RTCONFIG_PRELINK
#undef RTCONFIG_MSSID_PRELINK
#undef RTCONFIG_OPENSSL10
#undef RTCONFIG_NO_PTHREAD_TIMEDWAIT
#define RTCONFIG_OPEN_NAT 1
#define RTCONFIG_BRCM_HOSTAPD 1
#undef RTCONFIG_FRS_LIVE_UPDATE
#undef RTCONFIG_AUTO_FW_UPGRADE
#undef RTCONFIG_BETA_UPGRADE
#undef RTCONFIG_ROLLBACKFW
#undef RTCONFIG_REVERTFW
#define RTCONFIG_ASD 1
#undef RTCONFIG_LIVE_UPDATE_RSA
#define RTCONFIG_UUPLUGIN 1
#undef RTCONFIG_GEARUPPLUGIN
#undef RTCONFIG_TCPLUGIN
#undef RTCONFIG_TC_GAME_ACC
#undef RTCONFIG_TC_DOWNLOAD
#undef RTCONFIG_ATEFROMWAN
#undef RTCONFIG_WIFI_DRV_DISABLE
#undef RTCONFIG_BROOP
#undef RTCONFIG_BROOP_LED
#undef RTCONFIG_GN_WBL
#undef RTCONFIG_AMAZON_WSS
#define RTCONFIG_OOKLA 1
#undef RTCONFIG_OOKLA_LITE
#undef RTCONFIG_ETH_MONITOR
#undef RTCONFIG_QCA_MCSD
#undef RTCONFIG_QSDK6PLUS
#undef RTCONFIG_QSDK10CS
#undef RTCONFIG_AMAS_ADTBW
#undef RTCONFIG_AMAS_UNIQUE_MAC
#define RTCONFIG_ACCOUNT_BINDING 1
#define RTCONFIG_AMAS_SYNC_2G_BW 1
#undef RTCONFIG_NoETH
#undef RTCONFIG_TAIL_INFO
#define RTCONFIG_WL_SCHED_V2 1
#define RTCONFIG_PC_SCHED_V2 1
#define RTCONFIG_SCHED_V2 1
#define RTCONFIG_WL_SCHED_V3 1
#define RTCONFIG_PC_SCHED_V3 1
#undef RTCONFIG_SCHED_V3
#undef RTCONFIG_MULTIFW
#undef RTCONFIG_OVS
#undef RTCONFIG_OPENSYNC
#define RTCONFIG_RE_RECONNECT 1
#undef RTCONFIG_BH_SWITCH_ETH_FIRST
#define RTCONFIG_CAPTCHA 1
#undef RTCONFIG_MULTISERVICE_WAN
#define RTCONFIG_VIF_ONBOARDING 1
#undef RTCONFIG_OUTFOX
#undef RTCONFIG_DISAPPCAPT
#undef RTCONFIG_WIFI6E
#define RTCONFIG_WIFI7 1
#undef RTCONFIG_DISWIFI7
#undef RTCONFIG_UAWIFI
#undef RTCONFIG_QOSR1
#undef RTCONFIG_IPTABLES1810
#define RTCONFIG_MLO 1
#undef RTCONFIG_DIS_MLO_QIS
#define RTCONFIG_MLO_FH 1
#define RTCONFIG_MLO_BH 1
#undef RTCONFIG_SYSCLASSGPIO
#undef RTCONFIG_SAVE_WL_NVRAM_BOTH
#undef RTCONFIG_SWCONFIG
#undef RTCONFIG_MTK_NAND_BLOCK2
#undef RTCONFIG_QCA_PLC2
#undef RTCONFIG_VAR_NVRAM
#undef RTCONFIG_BCM_OAM
#define RTCONFIG_NEW_PHYMAP 1
#define RTCONFIG_LIB_CODB 1
#define RTCONFIG_INSTANT_GUARD 1
#define RTCONFIG_GAME_MODE 1
#define RTCONFIG_BHSWITCH_RE_SELFOPT 1
#define RTCONFIG_PREFERAP_RE_SELFOPT 1
#define RTCONFIG_SCHED_DAEMON 1
#define RTCONFIG_PC_REWARD 1
#define RTCONFIG_MAX_RE 16
#undef RTCONFIG_FRONTHAUL_DBG
#undef RTCONFIG_RALINK_BUILDIN_WIFI
#undef RTCONFIG_DLOADER
#undef RTCONFIG_FIBOCOM_FG621
#undef RTCONFIG_TIME_QUOTA
#undef RTCONFIG_QSDK_LM256
#define RTCONFIG_WIREGUARD 1
#define RTCONFIG_OWE_TRANS 1
#define RTCONFIG_TPVPN 1
#undef RTCONFIG_HMA
#define RTCONFIG_NORDVPN 1
#define RTCONFIG_SURFSHARK 1
#undef RTCONFIG_SPECIFIC_PPPOE
#define RTCONFIG_ACL96 1
#undef RTCONFIG_ISP_CUSTOMIZE_TOOL
#undef RTCONFIG_ISPCTRL
#define RTCONFIG_GOOGLE_ASST 1
#define RTCONFIG_EXTEND_LIMIT 1
#define RTCONFIG_COMFW 1
#define RTCONFIG_QUADBAND 1
#define RTCONFIG_LLDPD_0_9_8 1
#undef RTCONFIG_LLDPD_1_0_11
#define RTCONFIG_FSMD 1
#undef RTCONFIG_3LANPORT_DEVICE
#define RTCONFIG_DNS_PING 1
#undef RTCONFIG_CALC_NVRAM
#undef RTCONFIG_HW_DOG
#undef RTCONFIG_MSSID_REALMAC
#undef RTCONFIG_NCURSES_6_1
#undef RTCONFIG_GRE
#define RTCONFIG_AMAS_CENTRAL_CONTROL 1
#define RTCONFIG_BANDINDEX_NEW 1
#define RTCONFIG_AMAS_CAP_CONFIG 1
#undef RTCONFIG_AMAS_ENT_FRONTHAUL
#undef RTCONFIG_DEF_AUTO_FRONTHAUL
#undef RTCONFIG_DEF_ON_FRONTHAUL
#undef RTCONFIG_DEF_OFF_FRONTHAUL
#undef RTCONFIG_IG_SITE2SITE
#undef RTCONFIG_FRONTHAUL_AP_AUTO_OPT
#undef RTCONFIG_MT798X
#undef RTCONFIG_SECUREBOOT
#undef RTCONFIG_TRUSTZONE
#undef RTCONFIG_FSCRYPTCTL
#undef RTCONFIG_AVOID_TZ_ENV
#undef RTCONFIG_BSC_SR
#undef RTCONFIG_AMAS_DWB_RULE
#undef RTCONFIG_AMAS_CHANNEL_PLAN
#undef RTCONFIG_DUPVIF
#undef RTCONFIG_NEWSITE_PROVISIONING
#undef RTCONFIG_MULTISITEAPP
#undef RTCONFIG_AMAS_SS2
#undef RTCONFIG_AMAS_SYNC_LEDG
#define RTCONFIG_WPA3_ENTERPRISE 1
#undef RTCONFIG_MULTI_PPP
#undef RTCONFIG_AMAS_CENTRAL_OPTMZ
#undef RTCONFIG_DNSMQ_USER
#undef RTCONFIG_AMAS_CENTRAL_ADS
#undef RTCONFIG_NOWL
#undef RTCONFIG_INTEL_EVO
#undef RTCONFIG_SW_SPDLED
#undef RTCONFIG_BCM4906_504
#undef RTCONFIG_AMAS_UPLOAD_FILE
#undef RTCONFIG_HAS_6G
#undef RTCONFIG_HAS_6G_2
#undef RTCONFIG_CHECK_PAP_WPAPSK
#undef RTCONFIG_ECC256
#undef RTCONFIG_RTL_UMGMT
#define RTCONFIG_AUTO_WANPORT 1
#undef RTCONFIG_FU_TEST
#undef RTCONFIG_NVSW_IN_JFFS
#define RTCONFIG_AMAS_OB_DISABLE_DSAP 1
#undef RTCONFIG_HND_GPIO
#define RTCONFIG_PRESSURE_SENSOR 1
#undef RTCONFIG_BCM_AFC
#undef RTCONFIG_AFC_POSITIONING
#undef RTCONFIG_SMARTHAUL
#undef RTCONFIG_BRCM_SMARTHAUL
#undef RTCONFIG_MLO_BH_BAND
#undef RTCONFIG_DOWNGRADE_CHECK
#undef RTCONFIG_MLO_CONFIG_566
#undef RTCONFIG_MLO_CONFIG_556
#undef RTCONFIG_MLO_DEFAULT_ACTIVE
#undef RTCONFIG_NO_AIDISK
#undef RTCONFIG_FLASH_TYPE_EMMC
#undef RTCONFIG_JFFS_PARTITION
#undef RTCONFIG_KNV_BACKUP
#undef RTCONFIG_NV_BACKUP2
#undef RTCONFIG_DIS_HASH_KEY_GEN_CHECK
#undef RTCONFIG_ENERGY_SAVE
#undef RTCONFIG_CC3220
#define RTCONFIG_SECURE_BY_DEFAULT 1
#undef RTCONFIG_AURALED
#undef RTCONFIG_AURALED_NIGHT
#undef RTCONFIG_SINGLE_LED_NIGHT_MODE

#define RTCONFIG_OPENSSL35 1
