#!/bin/bash
# GT-BE98 kernel config helper (Asuswrt-Merlin / gnuton fork, HND 5.04 BE 4916)
#
#   ./kconfig.sh menu    open the kernel's real menuconfig, then save the result
#   ./kconfig.sh diff     show your kernel config deltas vs pristine upstream
#   ./kconfig.sh save     write kernel/linux-4.19/.config back to config_base.6a.6813
#   ./kconfig.sh apply    re-apply the saved fragment onto config_base (after a git checkout wiped it)
#   ./kconfig.sh reset    restore config_base.6a.6813 from git (discard your changes)
#
# Why this exists: kconfig only resolves the CONFIG_BCM_* symbols when it runs
# with the full Broadcom build environment (BRCM_CHIP, BCM_KF_*, LINUX_VER_STR,
# a seeded .config from setprofile). Run `make menuconfig` in kernel/linux-4.19
# directly and it silently drops ~190 CONFIG_BCM_ symbols -- the entire platform
# support. Everything here goes through `make kernel-menuconfig` in the SDK dir,
# which is the same path the real build uses.

set -euo pipefail

SRC="${AMNG_SRC:-$(cd "$(dirname "$0")/.." && pwd)}"
IMAGE="${AMNG_IMAGE:-amng-toolchains:ccache}"
MOUNT="/build/asuswrt-merlin.ng"
SDK="release/src-rt-5.04behnd.4916"
KB="$SDK/kernel/linux-4.19"
BASECFG_REL="$KB/config_base.6a.6813"     # per-chip (BCM6813) kernel config the build starts from
BASECFG="$SRC/$BASECFG_REL"
WORKCFG="$SRC/$KB/.config"
FRAG="${AMNG_FRAG:-$SRC/gt-be98-kernel.frag}"

SETUP='sudo ln -sfn /home/docker/am-toolchains/brcm-arm-hnd /opt/toolchains'

in_container() {   # $1 = tty flag, rest = command
    local tty="$1"; shift
    docker run --rm $tty \
        -v "$SRC:$MOUNT" -u docker:docker -w "$MOUNT" \
        -e "TERM=${TERM:-xterm-256color}" \
        "$IMAGE" bash -lc "$SETUP; cd '$MOUNT/$SDK'; $*"
}

BASELINE="$SRC/$KB/.config.kconfig-baseline"

# The build normalises the kernel config (olddefconfig collapses ~31 duplicate
# lines and drops prompt-less symbols). Diffing against raw git would bury your
# edits in that noise, so we snapshot the *normalised* config as the baseline.
pristine() { cat "$BASELINE"; }

symbols() { grep -E '^(CONFIG_[A-Z0-9_]+=|# CONFIG_[A-Z0-9_]+ is not set)' "$@" | sort -u; }

need_baseline() {
    [ -f "$BASELINE" ] || {
        echo "no baseline snapshot yet -- run './kconfig.sh menu' first" >&2
        exit 1
    }
}

show_diff() {
    need_baseline
    local tmp; tmp=$(mktemp)
    pristine > "$tmp"
    echo "=== kernel config deltas vs pristine $(basename "$BASECFG_REL") ==="
    if diff <(symbols "$tmp") <(symbols "$BASECFG") > /dev/null; then
        echo "(no changes)"
    else
        diff <(symbols "$tmp") <(symbols "$BASECFG") | grep -E '^[<>]' || true
    fi
    rm -f "$tmp"
}

write_frag() {
    need_baseline
    local tmp; tmp=$(mktemp)
    pristine > "$tmp"
    {
        echo "# GT-BE98 kernel config deltas vs upstream $(basename "$BASECFG_REL")"
        echo "# Generated by kconfig.sh -- lines below are YOUR changes only."
        echo
        diff <(symbols "$tmp") <(symbols "$BASECFG") | grep '^>' | sed 's/^> //' || true
    } > "$FRAG"
    rm -f "$tmp"
    echo "fragment written: $FRAG ($(grep -cE '^(CONFIG_|# CONFIG_)' "$FRAG" || echo 0) changed symbols)"
}

case "${1:-help}" in
  menu)
    echo ">> seeding + normalising kernel config (setprofile + olddefconfig)..."
    in_container "-i" "make kernel-config-prep" >/dev/null
    cp "$WORKCFG" "$BASELINE"
    echo ">> baseline snapshot taken ($(grep -cE '^CONFIG_[A-Z0-9_]+=' "$BASELINE") enabled symbols)"
    echo ">> opening kernel menuconfig (full BCM environment)..."
    in_container "-it" "make kernel-menuconfig"
    echo
    echo ">> saving $KB/.config -> $(basename "$BASECFG_REL")"
    cp "$WORKCFG" "$BASECFG"
    show_diff
    write_frag
    echo
    echo ">> now rebuild with:  ./amng.sh make PARALLEL_BUILD=-j\$(nproc) gt-be98"
    ;;
  save)
    [ -f "$WORKCFG" ] || { echo "no $WORKCFG -- run './kconfig.sh menu' first" >&2; exit 1; }
    cp "$WORKCFG" "$BASECFG"
    show_diff
    write_frag
    ;;
  diff)
    show_diff
    ;;
  apply)
    # Replay the fragment onto config_base. This is the recovery path when a
    # `git checkout -- .` (e.g. cleaning up a poisoned build) reverted
    # config_base but the fragment file survived outside the tree.
    [ -f "$FRAG" ] || { echo "no fragment at $FRAG" >&2; exit 1; }
    n=0
    while IFS= read -r line; do
        case "$line" in
            CONFIG_*=*)              sym="${line%%=*}" ;;
            "# CONFIG_"*" is not set") sym="${line#\# }"; sym="${sym%% *}" ;;
            *) continue ;;
        esac
        # drop any existing state for this symbol, then append the wanted one
        sed -i "/^${sym}=/d;/^# ${sym} is not set\$/d" "$BASECFG"
        printf '%s\n' "$line" >> "$BASECFG"
        n=$((n+1))
    done < "$FRAG"
    echo "applied $n symbols from $FRAG -> $(basename "$BASECFG_REL")"
    echo ">> rebuild to make it take effect:  ./amng.sh make PARALLEL_BUILD=-j88 gt-be98"
    ;;
  reset)
    git -C "$SRC" checkout -- "$BASECFG_REL"
    rm -f "$BASELINE"
    echo "restored $BASECFG_REL from git, baseline snapshot cleared"
    ;;
  *)
    sed -n '2,10p' "$0" | sed 's/^# \{0,1\}//'
    ;;
esac
