#!/usr/bin/env python3
"""Build target libgcc with the existing native-host compilers and glibc 2.44.

ARM support headers are generated by the matching upstream GCC make rules.
Only build-machine generators are compiled: the target compiler is the pinned
Ubuntu GCC 15.2 compiler, not a newly bootstrapped compiler. AArch64 reuses the
generated headers from the existing GCC 16.2 compiler that compiles its runtime.
All generated files and libgcc's implicit install-to-gcc stay in this checkpoint.
"""
import argparse
import json
import os
from pathlib import Path
import shlex
import shutil
import subprocess

p = argparse.ArgumentParser(description=__doc__)
p.add_argument('abi', choices=['armel', 'armhf', 'aarch64'])
p.add_argument('--jobs', type=int, default=4)
a = p.parse_args()
root = Path(__file__).resolve().parents[1]
ws = root.parent
cfg = json.loads((root / 'configs/build-targets.json').read_text())[a.abi]
env = dict(os.environ, LC_ALL='C')
if cfg['host_library_dir']:
    env['LD_LIBRARY_PATH'] = cfg['host_library_dir']
env['PATH'] = str(Path(cfg['tools']).parent) + ':' + env['PATH']
source = (ws / 'gcc162-usb/gcc-16.2.0' if a.abi == 'aarch64'
          else root / 'sources/gcc-15.2.0')
assert (source / 'gcc/BASE-VER').read_text().strip() == cfg['compiler_version']
obj = root / 'builds' / a.abi / 'gcc-runtime'
obj.mkdir(exist_ok=True)
commands = []

def run(args, cwd, label, extra_env=None):
    command = [str(x) for x in args]
    commands.append(dict(command=command, cwd=str(cwd)))
    (root / 'evidence' / (a.abi + '-libgcc-commands.json')).write_text(json.dumps(commands, indent=2) + '\n')
    print(a.abi, label, flush=True)
    with (root / 'evidence' / (a.abi + '-' + label + '.log')).open('w') as log:
        subprocess.run(command, cwd=cwd, env=extra_env or env, stdout=log,
                       stderr=subprocess.STDOUT, check=True)

gcc = obj / 'gcc'
if a.abi == 'aarch64':
    gcc.mkdir(exist_ok=True)
    # These are the exact generated headers belonging to our existing xgcc.
    # Copy rather than symlink: libgcc's "all" target installs into gcc_objdir.
    for header in (ws / 'gcc162-usb/obj/gcc').glob('*.h'):
        shutil.copy2(header, gcc / header.name)
    shutil.copy2(ws / 'gcc162-usb/obj/gcc/libgcc.mvars', gcc / 'libgcc.mvars')
else:
    old = ws / 'gcc162-usb'
    configure = [source / 'configure', '--build=aarch64-unknown-linux-gnu',
                 '--host=aarch64-unknown-linux-gnu', '--target=' + cfg['triplet'],
                 '--prefix=/usr/local', '--with-sysroot=' + cfg['sysroot'],
                 '--with-glibc-version=2.44', '--enable-languages=c,c++',
                 '--disable-bootstrap', '--disable-multilib', '--disable-nls',
                 '--disable-libsanitizer', '--disable-werror', '--enable-checking=release',
                 '--enable-threads=posix', '--enable-shared', '--enable-tls',
                 '--with-cpu=cortex-a53+crypto',
                 '--with-fpu=crypto-neon-fp-armv8',
                 '--with-float=' + ('hard' if a.abi == 'armhf' else 'softfp'),
                 '--with-as=' + cfg['tools'] + 'as', '--with-ld=' + cfg['tools'] + 'ld',
                 '--with-gmp-include=' + str(old / 'obj/gmp'),
                 '--with-gmp-lib=' + str(old / 'obj/gmp/.libs'),
                 '--with-mpfr-include=' + str(old / 'gcc-16.2.0/mpfr/src'),
                 '--with-mpfr-lib=' + str(old / 'obj/mpfr/src/.libs'),
                 '--with-mpc-include=' + str(old / 'gcc-16.2.0/mpc/src'),
                 '--with-mpc-lib=' + str(old / 'obj/mpc/src/.libs')]
    run(configure, obj, 'configure-support')
    if not (gcc / 'Makefile').exists():
        run(['make', '-j' + str(a.jobs), 'configure-gcc', 'all-build-libiberty', 'all-libiberty'], obj, 'configure-gcc-support')
    run(['make', '-j' + str(a.jobs), 'tconfig.h', 'tm.h', 'options.h',
         'insn-constants.h', 'insn-modes.h', 'arm-isa.h', 'arm-cpu.h',
         'version.h'],
        gcc, 'generate-target-headers')
    # Use the installed compiler's specs. -o suppresses *only* building a new
    # compiler/specs; the upstream rule still generates libgcc.mvars normally.
    (gcc / 'specs').write_bytes(subprocess.check_output([cfg['cc'], '-dumpspecs'], env=env))
    run(['make', '-o', 'xgcc', '-o', 'specs', 'libgcc.mvars',
         'CFLAGS_FOR_TARGET=-O2 -g -frecord-gcc-switches', 'INHIBIT_LIBC_CFLAGS='],
        gcc, 'generate-libgcc-mvars')

(gcc / 'include').mkdir(exist_ok=True)
lib = obj / cfg['triplet'] / 'libgcc'
lib.mkdir(parents=True, exist_ok=True)
target_env = dict(env, CC=cfg['cc'], CXX=cfg['cxx'],
                  CFLAGS='-O2 -g -frecord-gcc-switches',
                  CXXFLAGS='-O2 -g -frecord-gcc-switches',
                  LDFLAGS='-Wl,--build-id=sha1')
for key in ('AR', 'AS', 'LD', 'NM', 'RANLIB', 'STRIP'):
    target_env[key] = cfg['tools'] + key.lower()
if not (lib / 'Makefile').exists():
    run([source / 'libgcc/configure', '--build=aarch64-build-linux-gnu',
         '--host=' + cfg['triplet'], '--target=' + cfg['triplet'],
         '--prefix=/usr', '--libdir=/usr/lib/' + cfg['triplet'],
         '--with-sysroot=' + cfg['sysroot'], '--with-glibc-version=2.44',
         '--disable-multilib', '--enable-shared', '--enable-threads=posix',
         '--enable-tls', '--disable-werror'], lib, 'configure-libgcc', target_env)
run(['make', '-j' + str(a.jobs), 'all', 'gcc_objdir=' + str(gcc),
     'GCC_CFLAGS=-O2 -g -frecord-gcc-switches -DIN_GCC -isystem ./include',
     'INHIBIT_LIBC_CFLAGS=', 'LDFLAGS=-Wl,--build-id=sha1'],
    lib, 'build-libgcc', target_env)
assert (lib / 'libgcc_s.so.1').is_file()
print('BUILT', lib / 'libgcc_s.so.1', flush=True)
